### ISSUE TITLE
Cardiac Output and Cardiac Index

### ISSUE THREAD

**Issue by NichaA** [MIT-LCP/eicu-website#35]
There are many systems (e.g. right heart catheter, PICCO,NICOM, etc) and techniques (e.g. fick, thermodilution, etc.) that can measure and estimate the cardiac output. Is there any way to determine how the cardiac output and cardiac index in the vitalAperiodic table were measured in the eICU database?

**Comment by alistairewj** [comment]
Great question! @obadawi ?

**Comment by obadawi** [comment]
I don't believe there would be any way to track back to the source data for
that information. Only the values are stored after being received by the
interface.
