### ISSUE TITLE
Insurance information unavailable

### ISSUE THREAD

**Issue by sachin1t** [MIT-LCP/eicu-website#46]
I was not able to find any information regarding type of insurance the patients had. Is there any plan to include this information in the future?

**Comment by tompollard** [comment]
This information is not available to us unfortunately, so there is no plan to include it in future.

**Comment by tompollard** [comment]
(Please follow the instructions at: http://eicu-crd.mit.edu/help/ to post future questions. This website is intended for managing website content only).
